version: '3'
services:
    db:
        image: postgres:13
        environment:
            POSTGRES_HOST_AUTH_METHOD: 'trust'
    server:
        build:
            context: ./
            dockerfile: ./project/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./project:/project
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            DB_NAME: 'postgres'
            DB_USER: 'postgres'
            DB_PASSWORD: 'postgres'
            DB_HOST: 'db'
            SECRET: $SECRET
            RECAPTCHA_PRIVATE_KEY: $RECAPTCHA_PRIVATE_KEY
            RECAPTCHA_PUBLIC_KEY: $RECAPTCHA_PUBLIC_KEY
            TG_TOKEN: $TG_TOKEN
            TG_CHAT_ID: $TG_CHAT_ID
            EMAIL_HOST: $EMAIL_HOST
            EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
            ADMIN_PASSWORD: $ADMIN_PASSWORD
